/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.weka.gui;

import imsofa.weka.factory.LectureFactory;
import imsofa.weka.gui.model.lecture.Lecture;
import imsofa.weka.gui.model.lecture.LectureNodeRenderer;
import imsofa.weka.gui.model.lecture.LectureTreeModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author lendle
 */
public class MainLectureList extends javax.swing.JFrame {

    /**
     * Creates new form MainLectureList
     */
    public MainLectureList() {
        initComponents();
        reloadLectures();
        this.setLocationRelativeTo(null);
    }
    
    private void reloadLectures(){
        this.treeLectures.setModel(new LectureTreeModel(LectureFactory.newInstance().getLectures()));
        this.treeLectures.setCellRenderer(new LectureNodeRenderer());
        int rowCount=treeLectures.getRowCount();
        while(true){
            for(int i=0; i<rowCount; i++){
                treeLectures.expandRow(i);
            }
            if(treeLectures.getRowCount()!=rowCount){
                rowCount=treeLectures.getRowCount();
            }else{
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonLoad = new javax.swing.JButton();
        buttonReload = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        treeLecturesPane = new javax.swing.JScrollPane();
        treeLectures = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("選擇教程");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonLoad.setText("載入");
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLoad);

        buttonReload.setText("刷新");
        buttonReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReloadActionPerformed(evt);
            }
        });
        jPanel1.add(buttonReload);

        buttonExit.setText("離開");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        jPanel1.add(buttonExit);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        treeLectures.setRootVisible(false);
        treeLecturesPane.setViewportView(treeLectures);

        getContentPane().add(treeLecturesPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed
        // TODO add your handling code here:
        Object o=this.treeLectures.getSelectionPath().getLastPathComponent();
        if(o instanceof Lecture){
            Lecture lecture=(Lecture) o;
            final Main main=new Main(lecture.getHomeFolder());
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    main.setVisible(true);
                }
            });
        }
        
    }//GEN-LAST:event_buttonLoadActionPerformed

    private void buttonReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReloadActionPerformed
        // TODO add your handling code here:
        reloadLectures();
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
                treeLectures.updateUI();
            }
        });
    }//GEN-LAST:event_buttonReloadActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLectureList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLectureList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLectureList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLectureList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLectureList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLoad;
    private javax.swing.JButton buttonReload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTree treeLectures;
    private javax.swing.JScrollPane treeLecturesPane;
    // End of variables declaration//GEN-END:variables
}
