/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.weka.gui;

import imsofa.weka.validation.ValidationParameter;
import imsofa.weka.validation.ValidatorManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import weka.core.Instances;
import weka.gui.arffviewer.ArffSortedTableModel;

/**
 *
 * @author lendle
 */
public class ValidationPanel extends javax.swing.JPanel {
    private ModelingPanelContext ctx=null;
    /**
     * Creates new form ClusterValidationPanel
     */
    public ValidationPanel() {
        initComponents();
        
    }
    
    public void init(ModelingPanelContext ctx){
        this.ctx=ctx;
        for(File file : ctx.getLecture().getHomeFolder().listFiles()){
            if(file.getName().endsWith(".vmodel")){
                this.comboSavedValidationParameters.addItem(file.getName());
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new weka.gui.arffviewer.ArffTable();
        comboSavedValidationParameters = new javax.swing.JComboBox<>();
        buttonGo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(dataTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(comboSavedValidationParameters, java.awt.BorderLayout.NORTH);

        buttonGo.setText("Execute");
        buttonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoActionPerformed(evt);
            }
        });
        add(buttonGo, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoActionPerformed
        // TODO add your handling code here:
        try (ObjectInputStream input = new ObjectInputStream(new FileInputStream(new File(ctx.getLecture().getHomeFolder(), comboSavedValidationParameters.getSelectedItem().toString())))) {
            ValidationParameter vp=(ValidationParameter) input.readObject();
            Instances result=ValidatorManager.getInstance().validate(ctx.getInstances(), vp);
            ArffSortedTableModel model = new ArffSortedTableModel(result);
            this.dataTable.setModel(model);
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonGoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGo;
    private javax.swing.JComboBox<String> comboSavedValidationParameters;
    private weka.gui.arffviewer.ArffTable dataTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
