/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.weka.gui.decisiontree;

import javax.swing.JSpinner;

/**
 *
 * @author lendle
 */
public class J48OptionsPanel extends javax.swing.JPanel {

    public JSpinner getSpinnerConfidenceFactor() {
        return spinnerConfidenceFactor;
    }

    public JSpinner getSpinnerMinObjs() {
        return spinnerMinObjs;
    }
    
    /**
     * Creates new form J48OptionsPanel
     */
    public J48OptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spinnerConfidenceFactor = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spinnerMinObjs = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createTitledBorder("J48 設定"));

        jLabel1.setText("信心指標：");

        spinnerConfidenceFactor.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.25f), Float.valueOf(0.0f), Float.valueOf(1.0f), Float.valueOf(0.05f)));

        jLabel2.setText("最小節點：");

        spinnerMinObjs.setModel(new javax.swing.SpinnerNumberModel(5, 1, null, 1));
        spinnerMinObjs.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerMinObjs, "#############"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerConfidenceFactor, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerMinObjs))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerConfidenceFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerMinObjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JSpinner spinnerConfidenceFactor;
    private javax.swing.JSpinner spinnerMinObjs;
    // End of variables declaration//GEN-END:variables
}
