/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.weka.gui.decisiontree;

import javax.swing.JSpinner;

/**
 *
 * @author lendle
 */
public class RandomTreeOptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RandomTreeOptionsPanel
     */
    public RandomTreeOptionsPanel() {
        initComponents();
    }

    public JSpinner getSpinnerK() {
        return spinnerK;
    }

    public JSpinner getSpinnerMinObjs() {
        return spinnerMinObjs;
    }

    public JSpinner getSpinnerMinVariance() {
        return spinnerMinVariance;
    }

    public JSpinner getSpinnerMaxDepths() {
        return spinnerMaxDepths;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spinnerK = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinnerMinObjs = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinnerMinVariance = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spinnerMaxDepths = new javax.swing.JSpinner();

        jLabel2.setText("最小節點：");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Random Tree 設定"));

        jLabel1.setText("隨機屬性：");

        spinnerK.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spinnerK.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerK, "#####"));

        jLabel3.setText("最小節點：");

        spinnerMinObjs.setModel(new javax.swing.SpinnerNumberModel(5, 1, 100, 1));
        spinnerMinObjs.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerMinObjs, "#####"));

        jLabel4.setText("最小變異：");

        spinnerMinVariance.setModel(new javax.swing.SpinnerNumberModel(0.0010000000474974513d, 0.001d, 0.800000011920929d, 0.005d));
        spinnerMinVariance.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerMinVariance, "###.#####"));

        jLabel5.setText("最大深度：");

        spinnerMaxDepths.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        spinnerMaxDepths.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerMaxDepths, "#####"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerK))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerMinObjs))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerMinVariance, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerMaxDepths))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerMinObjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerMinVariance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(spinnerMaxDepths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    protected javax.swing.JSpinner spinnerK;
    protected javax.swing.JSpinner spinnerMaxDepths;
    protected javax.swing.JSpinner spinnerMinObjs;
    protected javax.swing.JSpinner spinnerMinVariance;
    // End of variables declaration//GEN-END:variables
}
