/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imsofa.weka.gui.clusterer;

import javax.swing.JComboBox;
import javax.swing.JSpinner;

/**
 *
 * @author lendle
 */
public class KmeansOptionsPanel extends javax.swing.JPanel {

   
    public JComboBox<String> getComboboxDistanceFunction() {
        return comboboxDistanceFunction;
    }

    public JSpinner getSpinnerClusters() {
        return spinnerClusters;
    }
    
    /**
     * Creates new form KmeansOptionsPanel
     */
    public KmeansOptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spinnerClusters = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        comboboxDistanceFunction = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder("K-means 設定"));

        jLabel1.setText("群組數量：");

        spinnerClusters.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));
        spinnerClusters.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerClusters, "#####"));

        jLabel2.setText("距離公式：");

        comboboxDistanceFunction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "尤拉距離", "曼哈頓距離" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerClusters))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxDistanceFunction, 0, 313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerClusters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboboxDistanceFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxDistanceFunction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spinnerClusters;
    // End of variables declaration//GEN-END:variables
}
